#!/usr/bin/env python3
"""
Phase 1 release smoke test for the capstone-self-healing platform.

This script validates the critical happy path:
1. Unified API health
2. Auth register/login (optional, if credentials provided)
3. Prompt creation
4. Plan generation
5. Test plan save/retrieve
6. Execution endpoint reachability

Usage:
  python tests/smoke_release_phase1.py --base-url http://localhost:8000
  python tests/smoke_release_phase1.py --base-url http://localhost:8000 --email user@example.com --password 'Secret123!'
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
import time
from dataclasses import dataclass
from typing import Optional, Dict, Any

import requests
import websockets


@dataclass
class SmokeConfig:
    base_url: str
    mcp_url: str
    email: Optional[str]
    password: Optional[str]
    timeout: int


class SmokeRunner:
    def __init__(self, cfg: SmokeConfig):
        self.cfg = cfg
        self.session = requests.Session()
        self.token: Optional[str] = None
        self.prompt_id: Optional[str] = None

    def _url(self, path: str) -> str:
        return f"{self.cfg.base_url.rstrip('/')}{path}"

    def _ok(self, name: str, detail: str = "") -> None:
        print(f"PASS  {name}{': ' + detail if detail else ''}")

    def _fail(self, name: str, detail: str = "") -> None:
        print(f"FAIL  {name}{': ' + detail if detail else ''}")
        raise RuntimeError(f"Smoke test failed at {name}: {detail}")

    def check_health(self) -> None:
        name = "health"
        try:
            res = self.session.get(self._url("/health"), timeout=self.cfg.timeout)
            if res.status_code != 200:
                self._fail(name, f"status={res.status_code} body={res.text[:240]}")
            self._ok(name)
        except Exception as exc:
            self._fail(name, str(exc))

    def check_mcp_health(self) -> None:
        name = "mcp.health"
        try:
            res = self.session.get(self._url("/mcp/health"), timeout=self.cfg.timeout)
            if res.status_code != 200:
                self._fail(name, f"status={res.status_code} body={res.text[:240]}")
            self._ok(name)
        except Exception as exc:
            self._fail(name, str(exc))

    def authenticate(self) -> None:
        if not self.cfg.email or not self.cfg.password:
            self._ok("auth", "skipped (no credentials provided)")
            return

        # Register first (idempotent behavior expected if user already exists)
        register_payload = {
            "email": self.cfg.email,
            "password": self.cfg.password,
            "confirm_password": self.cfg.password,
            "full_name": "Release Smoke User",
            "terms_accepted": True,
            "organization_name": "Smoke Org",
        }

        register_res = self.session.post(
            self._url("/api/v1/auth/register/organization"),
            json=register_payload,
            timeout=self.cfg.timeout,
        )

        # Accept either success or user-already-exists style errors
        if register_res.status_code not in (200, 201, 400, 409):
            self._fail("auth.register", f"status={register_res.status_code} body={register_res.text[:240]}")
        self._ok("auth.register", f"status={register_res.status_code}")

        login_res = self.session.post(
            self._url("/api/v1/auth/login"),
            json={"email": self.cfg.email, "password": self.cfg.password},
            timeout=self.cfg.timeout,
        )
        if login_res.status_code != 200:
            self._fail("auth.login", f"status={login_res.status_code} body={login_res.text[:240]}")

        body = login_res.json()
        token = body.get("access_token")
        if not token:
            self._fail("auth.login", "missing access_token")

        self.token = token
        self.session.headers.update({"Authorization": f"Bearer {token}"})
        self._ok("auth.login")

    def create_prompt(self) -> None:
        payload = {
            "prompt_text": "Login to the app and verify dashboard title",
            "title": f"Release Smoke Prompt {int(time.time())}",
            "description": "Generated by phase1 smoke script",
        }
        res = self.session.post(self._url("/api/v1/prompts"), json=payload, timeout=self.cfg.timeout)
        if res.status_code != 200:
            self._fail("prompts.create", f"status={res.status_code} body={res.text[:240]}")

        body = res.json()
        prompt_id = body.get("id") or body.get("prompt_id")
        if not prompt_id:
            self._fail("prompts.create", f"missing prompt id in response: {json.dumps(body)[:240]}")

        self.prompt_id = str(prompt_id)
        self._ok("prompts.create", f"prompt_id={self.prompt_id}")

    def generate_plan(self) -> Dict[str, Any]:
        res = self.session.post(
            self._url("/api/v1/plan"),
            json={"prompt": "login and verify dashboard"},
            timeout=self.cfg.timeout,
        )
        if res.status_code != 200:
            self._fail("plan.generate", f"status={res.status_code} body={res.text[:240]}")

        body = res.json()
        steps = body.get("steps") or body.get("actions") or []
        if not isinstance(steps, list) or len(steps) == 0:
            self._fail("plan.generate", "no steps/actions returned")

        self._ok("plan.generate", f"steps={len(steps)}")
        return {"steps": steps, "raw": body}

    def save_and_get_generated_plan(self, steps: list[Dict[str, Any]]) -> None:
        if not self.prompt_id:
            self._fail("generated-plan.save", "prompt_id unavailable")

        save_res = self.session.post(
            self._url("/generated-test-plans"),
            json={
                "prompt_id": self.prompt_id,
                "steps": steps,
                "plan_name": "Release Smoke Plan",
            },
            timeout=self.cfg.timeout,
        )
        if save_res.status_code != 200:
            self._fail("generated-plan.save", f"status={save_res.status_code} body={save_res.text[:240]}")
        self._ok("generated-plan.save")

        get_res = self.session.get(
            self._url(f"/generated-test-plans/by-prompt/{self.prompt_id}"),
            timeout=self.cfg.timeout,
        )
        if get_res.status_code != 200:
            self._fail("generated-plan.get", f"status={get_res.status_code} body={get_res.text[:240]}")

        data = get_res.json()
        plans = data.get("test_plans", [])
        if not isinstance(plans, list):
            self._fail("generated-plan.get", "test_plans is not a list")
        self._ok("generated-plan.get", f"plans={len(plans)}")

    def execution_endpoint_reachable(self) -> None:
        if not self.prompt_id:
            self._fail("execution.endpoint", "prompt_id unavailable")

        # Only validates endpoint contract reachability; execution may still fail due to runner state.
        res = self.session.post(
            self._url(f"/api/v1/execution/execute-prompt/{self.prompt_id}"),
            timeout=max(self.cfg.timeout, 30),
        )

        # Accept success and common known dependency failures as reachable-contract evidence.
        acceptable = {200, 400, 404, 500, 502, 503}
        if res.status_code not in acceptable:
            self._fail("execution.endpoint", f"unexpected status={res.status_code} body={res.text[:240]}")

        self._ok("execution.endpoint", f"status={res.status_code}")

    async def _mcp_request(self, ws, request_id: int, method: str, params: Dict[str, Any]) -> Dict[str, Any]:
        payload = {
            "jsonrpc": "2.0",
            "id": request_id,
            "method": method,
            "params": params,
        }
        await ws.send(json.dumps(payload))
        raw = await asyncio.wait_for(ws.recv(), timeout=self.cfg.timeout)
        return json.loads(raw)

    async def _mcp_contract_async(self) -> None:
        candidates = []
        if self.cfg.mcp_url:
            candidates.append(self.cfg.mcp_url)

        # Add common MCP websocket endpoints used in this repository.
        for candidate in [
            "ws://localhost:8001/mcp/ws",
            "ws://localhost:8001/ws",
            "ws://localhost:8001",
        ]:
            if candidate not in candidates:
                candidates.append(candidate)

        last_error = None
        for ws_url in candidates:
            try:
                async with websockets.connect(ws_url) as ws:
                    # tools/list contract
                    list_resp = await self._mcp_request(
                        ws,
                        1001,
                        "tools/list",
                        {"auth_token": "devtoken"},
                    )
                    if "error" in list_resp:
                        self._fail("mcp.tools.list", f"url={ws_url} error={list_resp['error']}")

                    tools = list_resp.get("result", [])
                    if not isinstance(tools, list) or len(tools) == 0:
                        self._fail("mcp.tools.list", f"url={ws_url} returned empty/non-list result")

                    tool_names = {t.get("name") for t in tools if isinstance(t, dict)}
                    if "context.put" not in tool_names:
                        self._fail("mcp.tools.list", f"url={ws_url} missing expected tool context.put")

                    self._ok("mcp.tools.list", f"url={ws_url} tools={len(tool_names)}")

                    # tools/call contract using a side-effect-free context call
                    call_resp = await self._mcp_request(
                        ws,
                        1002,
                        "tools/call",
                        {
                            "auth_token": "devtoken",
                            "name": "context.put",
                            "arguments": {
                                "key": "phase1_smoke",
                                "value": "ok",
                                "type": "string",
                            },
                        },
                    )

                    if "error" in call_resp:
                        self._fail("mcp.tools.call", f"url={ws_url} error={call_resp['error']}")

                    result = call_resp.get("result", {})
                    if not isinstance(result, dict) or result.get("ok") is not True:
                        self._fail("mcp.tools.call", f"url={ws_url} unexpected result={result}")

                    self._ok("mcp.tools.call", f"url={ws_url}")
                    return
            except Exception as exc:
                last_error = exc

        self._fail("mcp.connect", f"unable to connect to MCP websocket candidates: {last_error}")

    def mcp_contract_checks(self) -> None:
        try:
            asyncio.run(self._mcp_contract_async())
        except RuntimeError:
            loop = asyncio.new_event_loop()
            try:
                loop.run_until_complete(self._mcp_contract_async())
            finally:
                loop.close()

    def run(self) -> None:
        self.check_health()
        self.check_mcp_health()
        self.mcp_contract_checks()
        self.authenticate()
        self.create_prompt()
        plan = self.generate_plan()
        self.save_and_get_generated_plan(plan["steps"])
        self.execution_endpoint_reachable()


def parse_args() -> SmokeConfig:
    parser = argparse.ArgumentParser(description="Phase 1 release smoke test")
    parser.add_argument("--base-url", default=os.getenv("SMOKE_BASE_URL", "http://localhost:8000"))
    parser.add_argument("--mcp-url", default=os.getenv("SMOKE_MCP_URL", "ws://localhost:8001/mcp/ws"))
    parser.add_argument("--email", default=os.getenv("SMOKE_EMAIL"))
    parser.add_argument("--password", default=os.getenv("SMOKE_PASSWORD"))
    parser.add_argument("--timeout", type=int, default=int(os.getenv("SMOKE_TIMEOUT", "20")))

    args = parser.parse_args()
    return SmokeConfig(
        base_url=args.base_url,
        mcp_url=args.mcp_url,
        email=args.email,
        password=args.password,
        timeout=args.timeout,
    )


def main() -> int:
    cfg = parse_args()
    print("Starting Phase 1 smoke test")
    print(f"Base URL: {cfg.base_url}")

    try:
        SmokeRunner(cfg).run()
        print("\nRelease smoke test completed successfully")
        return 0
    except Exception as exc:
        print(f"\nRelease smoke test failed: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
